#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2024-2026 Chimera-NAS Project Contributors
#
# SPDX-License-Identifier: Unlicense
"""Rewrite SMBTORTURE_SUITES + SMBTORTURE_ENABLED_<backend> blocks in
   src/server/smb/tests/CMakeLists.txt from a smbtorture matrix run.

   Inputs:
       --subs       path to a one-per-line catalog of addressable subtests
                    (output of `smbtorture --list smb2.*` w/ trailing dup
                    stripped)
       --results    path to a `PASS|FAIL|TIME|SKIP|<backend>|<subtest>` log
       --cmake      path to src/server/smb/tests/CMakeLists.txt

   The script splices a single contiguous block that contains the suite list
   and all six per-backend allowlists, replacing whatever lies between the
   anchor markers `# >>> SMBTORTURE_BLOCK_BEGIN` and `# >>> SMBTORTURE_BLOCK_END`.
"""

import argparse, collections, sys

BACKENDS = ("memfs","linux","io_uring","cairn","diskfs_io_uring","diskfs_aio")
BEGIN = "# >>> SMBTORTURE_BLOCK_BEGIN (regenerate with tools/smbtorture/regen.sh)"
END   = "# >>> SMBTORTURE_BLOCK_END"


def parse_results(path):
    res = {}
    with open(path) as f:
        for line in f:
            parts = line.rstrip().split("|")
            if not parts or parts[0] not in ("PASS","FAIL","TIME","SKIP"):
                continue
            if len(parts) < 3:
                continue
            res[(parts[1], parts[2])] = parts[0]
    return res


def cmake_quote(s):
    return f'"{s}"' if any(c in s for c in ' ()') else s


def emit_block(subs, res):
    by_suite = collections.defaultdict(list)
    for s in subs:
        bits = s.split(".")
        parent = bits[0] + "." + bits[1]
        by_suite[parent].append(s)

    out = []
    w = out.append
    w(BEGIN)
    w("# Every smb2.* atomic subtest the Samba smbtorture client knows about,")
    w("# one ctest per (subtest, backend).  Generated by tools/smbtorture/regen.sh.")
    w("set(SMBTORTURE_SUITES")
    for parent in sorted(by_suite):
        w(f"    # {parent}")
        for s in sorted(by_suite[parent]):
            w(f"    {cmake_quote(s)}")
    w(")")
    w("")
    for b in BACKENDS:
        enabled = sorted([s for s in subs if res.get((b,s)) == "PASS"])
        w(f"set(SMBTORTURE_ENABLED_{b}")
        cur = None
        for s in enabled:
            bits = s.split(".")
            parent = bits[0] + "." + bits[1]
            if parent != cur:
                cur = parent
                w(f"    # {parent}")
            w(f"    {cmake_quote(s)}")
        w(")")
        w("")
    w(END)
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--subs", required=True)
    ap.add_argument("--results", required=True)
    ap.add_argument("--cmake", required=True)
    args = ap.parse_args()

    subs = [l.strip() for l in open(args.subs) if l.strip()]
    res = parse_results(args.results)
    block = emit_block(subs, res)

    txt = open(args.cmake).read()
    if BEGIN not in txt or END not in txt:
        print(f"error: anchor markers not found in {args.cmake}", file=sys.stderr)
        sys.exit(1)
    head, _, rest = txt.partition(BEGIN)
    _, _, tail = rest.partition(END)
    new = head + block + tail
    open(args.cmake, "w").write(new)
    n_pass = sum(1 for v in res.values() if v == "PASS")
    print(f"rewrote {args.cmake}: {len(subs)} subtests, {n_pass} pass cells")


if __name__ == "__main__":
    main()
