# SPDX-FileCopyrightText: 2026 Chimera-NAS Project Contributors
# SPDX-License-Identifier: LGPL-2.1-only
cmake_minimum_required(VERSION 3.22)
project(chimera_crypto_tests C)
set(CMAKE_C_STANDARD 11)
set(CMAKE_C_STANDARD_REQUIRED ON)
enable_testing()
get_filename_component(CHIMERA_SOURCE_ROOT "${CMAKE_CURRENT_SOURCE_DIR}/../../../.." ABSOLUTE)
include(${CHIMERA_SOURCE_ROOT}/src/common/crypto.cmake)
add_executable(crypto_test ../crypto_test.c)
target_link_libraries(crypto_test PRIVATE chimera_crypto)
if(MSVC)
    target_compile_definitions(crypto_test PRIVATE _CRT_SECURE_NO_WARNINGS)
    target_compile_options(chimera_crypto PRIVATE /W4 /WX /experimental:c11atomics)
    target_compile_options(crypto_test PRIVATE /W4 /WX /experimental:c11atomics /UNDEBUG)
else()
    target_compile_options(chimera_crypto PRIVATE -Wall -Wextra -Werror)
    target_compile_options(crypto_test PRIVATE -Wall -Wextra -Werror -UNDEBUG)
endif()
add_test(NAME chimera/crypto COMMAND crypto_test)
