/* SPDX-FileCopyrightText: 2026 Chimera-NAS Project Contributors
 *
 * SPDX-License-Identifier: LGPL-2.1-only
 *
 * SMB2 model-based-testing replayer (ROADMAP-SMB.md Increment 3): reads an
 * ITF trace generated by the Quint model (smb2_run.qnt) and replays every
 * message against the live in-process chimera SMB server, comparing each
 * command's reply to the model's baked-in expected result.  Any divergence
 * from the spec-first model is a mismatch; analyzed divergences are
 * reconciled against DEVIATIONS-SMB.md, never silently.
 *
 * Identity indirection (the harness's job, same pattern as the NFS suites):
 * the model names sessions, trees and handles by small integers; the
 * replayer learns the wire values (SessionId, TreeId, the opaque 16-byte
 * FileId) from replies and maps them.  CREATE targets a name directly (the
 * model already works in names).  Block symbols expand to bytes: symbol s at
 * block index i is a BS-byte block of byte value s (0 = a hole, reads zero).
 *
 * This replayer builds session/tree bootstrap, the file CREATE
 * disposition/share matrix, CLOSE, READ, WRITE and compounds on the wire.
 * The generated base corpus uses the `stepCore` flavor (delete-on-close
 * excluded until a ground-truth probe pins its removal timing -- see
 * DEVIATIONS-SMB.md Q-1).  Locks, set/query-info, rename and the oplock/lease
 * break lifecycle extend the replayer in a later pass.
 */

#include "smb2_mbt_common.h"

#include <stdarg.h>
#include <jansson.h>

#define BS       64              /* bytes per model block symbol */
#define MAX_SESS 16
#define MAX_TREE 16
#define MAX_FID  1024

static struct smb2_env   g_env;
static struct smb2_conn *g_conn_for_sess[MAX_SESS];
static uint32_t          g_wire_tree[MAX_TREE];
static uint8_t           g_wire_fid[MAX_FID][16];
static const char       *g_trace;
static int               g_nmismatch;

/* ---- ITF helpers -------------------------------------------------------- */

/* An ITF integer is {"#bigint":"N"} (or a bare JSON integer). */
static int64_t
jint(json_t *o)
{
    if (json_is_object(o)) {
        json_t *b = json_object_get(o, "#bigint");
        if (b) {
            return (int64_t) strtoll(json_string_value(b), NULL, 10);
        }
    }
    if (json_is_integer(o)) {
        return json_integer_value(o);
    }
    return 0;
} /* jint */

static int64_t
jfield(
    json_t     *o,
    const char *k)
{
    return jint(json_object_get(o, k));
} /* jfield */

static const char *
jtag(json_t *o)
{
    return json_string_value(json_object_get(o, "tag"));
} /* jtag */

static json_t *
jval(json_t *o)
{
    return json_object_get(o, "value");
} /* jval */

static int
jbool(
    json_t     *o,
    const char *k)
{
    return json_is_true(json_object_get(o, k));
} /* jbool */

static void
mism(
    const char *fmt,
    ...)
{
    va_list ap;

    printf("MISMATCH [%s] ", g_trace);
    va_start(ap, fmt);
    vprintf(fmt, ap);
    va_end(ap);
    printf("\n");
    g_nmismatch++;
} /* mism */

/* ---- model -> wire field maps ------------------------------------------- */

static uint32_t
disp_wire(const char *tag)
{
    if (strcmp(tag, "DispOpen") == 0) {
        return FILE_OPEN;
    }
    if (strcmp(tag, "DispCreate") == 0) {
        return FILE_CREATE;
    }
    if (strcmp(tag, "DispOpenIf") == 0) {
        return FILE_OPEN_IF;
    }
    if (strcmp(tag, "DispOverwrite") == 0) {
        return FILE_OVERWRITE;
    }
    if (strcmp(tag, "DispOverwriteIf") == 0) {
        return FILE_OVERWRITE_IF;
    }
    if (strcmp(tag, "DispSupersede") == 0) {
        return FILE_SUPERSEDE;
    }
    return FILE_OPEN_IF;
} /* disp_wire */

/* DesiredAccess: r->READ_DATA, w->WRITE_DATA, h->READ_ATTRIBUTES (a stat/
 * attr-only open that bypasses share arbitration), d->DELETE. */
static uint32_t
access_wire(json_t *a)
{
    uint32_t m = 0x00000080u;   /* FILE_READ_ATTRIBUTES always present */

    if (jbool(a, "r")) {
        m |= 0x00000001u;       /* FILE_READ_DATA */
    }
    if (jbool(a, "w")) {
        m |= 0x00000002u;       /* FILE_WRITE_DATA */
    }
    if (jbool(a, "d")) {
        m |= 0x00010000u;       /* DELETE */
    }
    return m;
} /* access_wire */

static uint32_t
share_wire(json_t *s)
{
    uint32_t m = 0;

    if (jbool(s, "r")) {
        m |= FILE_SHARE_READ;
    }
    if (jbool(s, "w")) {
        m |= FILE_SHARE_WRITE;
    }
    if (jbool(s, "d")) {
        m |= FILE_SHARE_DELETE;
    }
    return m;
} /* share_wire */

static uint8_t
sym_byte(int64_t s)
{
    return (uint8_t) (s == 0 ? 0 : s);
} /* sym_byte */

/* ---- per-command replay + compare --------------------------------------- */

/* Resolve a FidSel (FidRelated -> the current compound's CREATE fid; FidRef k
 * -> the learned wire FileId for model fid k). */
static const uint8_t *
resolve_fid(
    json_t        *sel,
    const uint8_t *related_fid,
    int            have_related)
{
    if (strcmp(jtag(sel), "FidRelated") == 0) {
        return have_related ? related_fid : NULL;
    }
    int64_t k = jint(jval(sel));
    if (k < 0 || k >= MAX_FID) {
        return NULL;
    }
    return g_wire_fid[k];
} /* resolve_fid */

/* Effective caching bits the wire granted (0 = none). */
static int
wire_caches(const struct smb2_create_out *o)
{
    if (o->oplock == SMB2_OPLOCK_LEVEL_NONE) {
        return 0;
    }
    if (o->oplock == SMB2_OPLOCK_LEVEL_LEASE) {
        return o->lease_state != 0;
    }
    return 1;   /* II / exclusive / batch all cache */
} /* wire_caches */

static void
do_create(
    struct smb2_conn *c,
    json_t           *v,
    json_t           *res)
{
    const char            *name  = json_string_value(json_object_get(v, "name"));
    uint32_t               disp  = disp_wire(jtag(json_object_get(v, "disp")));
    uint32_t               acc   = access_wire(json_object_get(v, "access"));
    uint32_t               shr   = share_wire(json_object_get(v, "share"));
    int                    doc   = jbool(v, "delOnClose");
    int                    isdir = jbool(v, "isDir");
    uint32_t               opts  = isdir ? FILE_DIRECTORY_FILE
                                        : FILE_NON_DIRECTORY_FILE;
    struct smb2_create_out out;

    if (doc) {
        opts |= FILE_DELETE_ON_CLOSE;
    }

    smb2_create_opts(c, name, disp, acc, shr, opts, NULL, &out);

    json_t                *rv     = jval(res);
    uint32_t               exp_st = (uint32_t) jfield(rv, "st");

    if (out.status != exp_st) {
        mism("CREATE '%s' status: model 0x%08x wire 0x%08x", name, exp_st,
             out.status);
        return;
    }
    if (out.status != ST_SUCCESS) {
        return;
    }

    uint32_t    exp_act = (uint32_t) jfield(rv, "act");
    if (out.action != exp_act) {
        mism("CREATE '%s' action: model %u wire %u", name, exp_act, out.action);
    }
    /* The base instance grants no caching; the wire must agree. */
    const char *ctag = jtag(json_object_get(rv, "caching"));
    if (strcmp(ctag, "CNone") == 0 && wire_caches(&out)) {
        mism("CREATE '%s' caching: model CNone but wire granted oplock 0x%02x "
             "lease 0x%02x", name, out.oplock, out.lease_state);
    }
    /* Learn the FileId for the model fid this CREATE produced. */
    int64_t     fid = jfield(rv, "fid");
    if (fid >= 0 && fid < MAX_FID) {
        memcpy(g_wire_fid[fid], out.file_id, 16);
    }
} /* do_create */

static void
do_close(
    struct smb2_conn *c,
    json_t           *v,
    json_t           *res,
    const uint8_t    *related_fid,
    int               have_related)
{
    const uint8_t *fid    = resolve_fid(v, related_fid, have_related);
    uint32_t       exp_st = (uint32_t) jfield(jval(res), "st");
    uint32_t       st;

    if (!fid) {
        mism("CLOSE: unresolved FileId");
        return;
    }
    st = smb2_close(c, fid);
    if (st != exp_st) {
        mism("CLOSE status: model 0x%08x wire 0x%08x", exp_st, st);
    }
} /* do_close */

static void
do_write(
    struct smb2_conn *c,
    json_t           *v,
    json_t           *res,
    const uint8_t    *related_fid,
    int               have_related)
{
    const uint8_t *fid = resolve_fid(json_object_get(v, "fid"), related_fid,
                                     have_related);
    int64_t        off    = jfield(v, "off");
    int64_t        len    = jfield(v, "len");
    int64_t        pat    = jfield(v, "pat");
    uint32_t       exp_st = (uint32_t) jfield(jval(res), "st");
    uint8_t        buf[16 * BS];
    uint32_t       count = 0, st;

    if (!fid) {
        mism("WRITE: unresolved FileId");
        return;
    }
    memset(buf, sym_byte(pat), (size_t) len * BS);
    st = smb2_write(c, fid, (uint64_t) off * BS, buf, (uint32_t) (len * BS),
                    &count);
    if (st != exp_st) {
        mism("WRITE status: model 0x%08x wire 0x%08x", exp_st, st);
        return;
    }
    if (st == ST_SUCCESS) {
        int64_t exp_count = jfield(jval(res), "count");   /* in blocks */
        if ((int64_t) count != exp_count * BS) {
            mism("WRITE count: model %lld blocks (%lld bytes) wire %u bytes",
                 (long long) exp_count, (long long) exp_count * BS, count);
        }
    }
} /* do_write */

static void
do_read(
    struct smb2_conn *c,
    json_t           *v,
    json_t           *res,
    const uint8_t    *related_fid,
    int               have_related)
{
    const uint8_t *fid = resolve_fid(json_object_get(v, "fid"), related_fid,
                                     have_related);
    int64_t        off    = jfield(v, "off");
    int64_t        len    = jfield(v, "len");
    json_t        *rv     = jval(res);
    uint32_t       exp_st = (uint32_t) jfield(rv, "st");
    uint8_t        buf[16 * BS];
    uint32_t       rlen = 0, st;

    if (!fid) {
        mism("READ: unresolved FileId");
        return;
    }
    st = smb2_read(c, fid, (uint64_t) off * BS, (uint32_t) (len * BS), buf,
                   &rlen);
    if (st != exp_st) {
        mism("READ status: model 0x%08x wire 0x%08x", exp_st, st);
        return;
    }
    if (st != ST_SUCCESS) {
        return;
    }

    int64_t exp_count = jfield(rv, "count");     /* blocks */
    int     exp_eof   = jbool(rv, "eof");
    if ((int64_t) (rlen / BS) != exp_count) {
        mism("READ count: model %lld blocks wire %u blocks",
             (long long) exp_count, rlen / BS);
    }
    /* Per-block symbol comparison. */
    json_t *blocks = json_object_get(rv, "blocks");
    size_t  nb     = json_array_size(blocks);
    for (size_t i = 0; i < nb && (i + 1) * BS <= rlen; i++) {
        uint8_t want = sym_byte(jint(json_array_get(blocks, i)));
        for (int j = 0; j < BS; j++) {
            if (buf[i * BS + j] != want) {
                mism("READ block %zu: model symbol byte 0x%02x wire 0x%02x",
                     i, want, buf[i * BS + j]);
                break;
            }
        }
    }
    (void) exp_eof;   /* eof already implied by count vs request length */
} /* do_read */

/* Dispatch one command; returns its wire status so a related compound can
 * stop on the first error (SMB2 first-error-stops). */
static void
dispatch_cmd(
    json_t  *cmd,
    json_t  *res,
    int64_t  sess,
    int64_t  tree,
    uint8_t *related_fid,
    int     *have_related)
{
    const char       *tag = jtag(cmd);
    json_t           *v   = jval(cmd);
    struct smb2_conn *c   =
        (sess >= 0 && sess < MAX_SESS) ? g_conn_for_sess[sess] : NULL;

    if (c && tree >= 0 && tree < MAX_TREE) {
        c->tree_id = g_wire_tree[tree];
    }

    if (strcmp(tag, "CSessionSetup") == 0) {
        struct smb2_conn *nc     = smb2_conn_open(&g_env);
        uint32_t          exp_st = (uint32_t) jfield(jval(res), "st");
        uint32_t          st;
        smb2_negotiate(nc);
        st = smb2_session_setup(nc);
        if (st != exp_st) {
            mism("SESSION_SETUP status: model 0x%08x wire 0x%08x", exp_st, st);
        }
        int64_t           rs = jfield(jval(res), "sess");
        if (rs >= 0 && rs < MAX_SESS) {
            g_conn_for_sess[rs] = nc;
        }
    } else if (strcmp(tag, "CTreeConnect") == 0) {
        uint32_t exp_st = (uint32_t) jfield(jval(res), "st");
        uint32_t st;
        if (!c) {
            mism("TREE_CONNECT: no connection for session %lld",
                 (long long) sess);
            return;
        }
        st = smb2_tree_connect(c, "\\\\server\\share");
        if (st != exp_st) {
            mism("TREE_CONNECT status: model 0x%08x wire 0x%08x", exp_st, st);
        }
        int64_t rt = jfield(jval(res), "tree");
        if (rt >= 0 && rt < MAX_TREE) {
            g_wire_tree[rt] = c->tree_id;
        }
    } else if (strcmp(tag, "CCreate") == 0) {
        if (!c) {
            mism("CREATE: no connection for session %lld", (long long) sess);
            return;
        }
        do_create(c, v, res);
        /* thread the FileId to the rest of a related compound */
        int64_t fid = jfield(jval(res), "fid");
        if (fid >= 0 && fid < MAX_FID &&
            (uint32_t) jfield(jval(res), "st") == ST_SUCCESS) {
            memcpy(related_fid, g_wire_fid[fid], 16);
            *have_related = 1;
        }
    } else if (strcmp(tag, "CClose") == 0) {
        do_close(c, v, res, related_fid, *have_related);
    } else if (strcmp(tag, "CWrite") == 0) {
        do_write(c, v, res, related_fid, *have_related);
    } else if (strcmp(tag, "CRead") == 0) {
        do_read(c, v, res, related_fid, *have_related);
    } else {
        mism("unhandled command tag '%s' (extend the replayer)", tag);
    }
} /* dispatch_cmd */

static void
do_message(json_t *lmsg_value)
{
    json_t *msg     = json_object_get(lmsg_value, "msg");
    json_t *results = json_object_get(lmsg_value, "results");
    json_t *cmds    = json_object_get(msg, "cmds");
    int64_t sess    = jfield(msg, "sess");
    int64_t tree    = jfield(msg, "tree");
    uint8_t related_fid[16];
    int     have_related = 0;

    /* The model truncates a related compound's results at the first error, so
     * iterating over the executed results replays exactly what the model ran
     * (both related first-error-stops and full unrelated compounds). */
    size_t  n = json_array_size(results);

    for (size_t i = 0; i < n && i < json_array_size(cmds); i++) {
        dispatch_cmd(json_array_get(cmds, i), json_array_get(results, i),
                     sess, tree, related_fid, &have_related);
    }
} /* do_message */

/* ---- trace driver ------------------------------------------------------- */

static const char *
find_lastop_key(json_t *state)
{
    const char *key;
    json_t     *val;

    json_object_foreach(state, key, val)
    {
        if (strstr(key, "::lastOp")) {
            return key;
        }
    }
    return NULL;
} /* find_lastop_key */

/* Pull the LInit capability profile from a trace's state 0. */
static int
read_caps(
    const char           *path,
    struct smb2_env_opts *opts)
{
    json_error_t err;
    json_t      *root = json_load_file(path, 0, &err);

    if (!root) {
        fprintf(stderr, "failed to parse %s: %s\n", path, err.text);
        return -1;
    }

    json_t      *states = json_object_get(root, "states");
    const char  *lokey  = (states && json_array_size(states))
        ? find_lastop_key(json_array_get(states, 0)) : NULL;
    if (!lokey) {
        fprintf(stderr, "no lastOp key in %s\n", path);
        json_decref(root);
        return -1;
    }

    json_t      *init = json_object_get(json_array_get(states, 0), lokey);
    if (strcmp(jtag(init), "LInit") != 0) {
        fprintf(stderr, "state 0 of %s is not LInit\n", path);
        json_decref(root);
        return -1;
    }

    json_t      *caps = json_object_get(jval(init), "caps");
    opts->oplocks            = jbool(caps, "oplocks");
    opts->leases             = jbool(caps, "leases");
    opts->directory_leases   = jbool(caps, "dirLeases");
    opts->persistent_handles = jbool(caps, "durable");
    json_decref(root);
    return 0;
} /* read_caps */

/* Replay one trace against the already-open g_env on a fresh per-trace
 * filesystem `fsname`.  Returns the trace's mismatch count (0 = clean). */
static int
run_trace(
    const char *fsname,
    const char *path)
{
    json_error_t err;
    json_t      *root = json_load_file(path, 0, &err);

    if (!root) {
        fprintf(stderr, "failed to parse %s: %s\n", path, err.text);
        return 1;
    }

    json_t      *states = json_object_get(root, "states");
    size_t       ns     = json_array_size(states);
    if (ns == 0) {
        fprintf(stderr, "trace %s has no states\n", path);
        json_decref(root);
        return 1;
    }

    const char  *lokey = find_lastop_key(json_array_get(states, 0));
    if (!lokey) {
        fprintf(stderr, "no lastOp key in %s\n", path);
        json_decref(root);
        return 1;
    }

    /* Fresh identity mappings + mismatch tally for this trace: a unique
     * fsname isolates the filesystem, and zeroing the wire-value maps stops a
     * stale SessionId/TreeId/FileId from a prior trace being reused. */
    memset(g_conn_for_sess, 0, sizeof(g_conn_for_sess));
    memset(g_wire_tree, 0, sizeof(g_wire_tree));
    memset(g_wire_fid, 0, sizeof(g_wire_fid));
    g_trace     = path;
    g_nmismatch = 0;

    smb2_env_fs_setup(&g_env, fsname);

    for (size_t i = 1; i < ns; i++) {
        json_t *lo = json_object_get(json_array_get(states, i), lokey);
        if (!lo || strcmp(jtag(lo), "LMsg") != 0) {
            continue;
        }
        do_message(jval(lo));
    }

    smb2_conn_reset(&g_env);
    smb2_env_fs_teardown(&g_env, fsname);

    int nm = g_nmismatch;
    if (nm) {
        fprintf(stderr, "%d mismatch(es) in %s\n", nm, path);
    } else {
        printf("ok: %s replayed with no mismatches\n", path);
    }
    json_decref(root);
    return nm;
} /* run_trace */

int
main(
    int   argc,
    char *argv[])
{
    const char          *traces[512];
    int                  ntraces = 0;
    struct smb2_env_opts opts    = { 0 };

    for (int i = 1; i < argc; i++) {
        if (strcmp(argv[i], "--trace") == 0 && i + 1 < argc) {
            if (ntraces < (int) (sizeof(traces) / sizeof(traces[0]))) {
                traces[ntraces++] = argv[++i];
            } else {
                i++;
            }
        }
    }
    if (ntraces == 0) {
        fprintf(stderr, "usage: %s --trace <file.itf.json> [--trace ...]\n",
                argv[0]);
        return 2;
    }

    /* Every trace in one batch shares a capability profile (one profile per
     * generation instance -- see smb2_mbt_add_batch in CMakeLists), so the
     * shared server is configured once from the first trace's LInit. */
    if (read_caps(traces[0], &opts) != 0) {
        return 2;
    }

    smb2_env_open_opts(&g_env, &opts);

    int total = 0;
    for (int i = 0; i < ntraces; i++) {
        char fsname[32];
        snprintf(fsname, sizeof(fsname), "fs_%d", i);
        total += run_trace(fsname, traces[i]);
    }

    smb2_env_stop(&g_env);

    if (total) {
        fprintf(stderr, "%d total mismatch(es) across %d trace(s)\n",
                total, ntraces);
        return 1;
    }
    printf("ok: %d trace(s) replayed with no mismatches\n", ntraces);
    return 0;
} /* main */
