# SPDX-FileCopyrightText: 2026 Chimera-NAS Project Contributors
#
# SPDX-License-Identifier: LGPL-2.1-only
#
# Resolve the model-based-test trace corpus for the quint suites.  The traces
# are generated by the chimera-nas/specs repo (submodule at ext/specs); this
# module makes them available to the chimera build as SPECS_BUNDLE_DIR -- a
# directory holding one subdirectory per suite (posix/ nfs3/ nfs4/ smb2/
# portmap/), each full of *.itf.json.  The quint suites point their replay
# ctests at that directory with the replayers' --trace-dir option, so the corpus
# does not have to be enumerated at configure time (the files do not exist until
# the bundle is built or fetched during the build).
#
# Two providers, selected by SPECS_BUNDLE (AUTO default):
#
#   * fetch -- when the submodule is clean, pull the prebuilt bundle the specs
#     CI published for that exact commit (ghcr.io/chimera-nas/specs:<sha>) with
#     oras and unpack it.  No quint/python needed; seconds instead of minutes.
#   * local -- build ext/specs in-tree (add_subdirectory).  Needed for spec
#     development (a dirty submodule, so no matching published bundle) or when
#     no bundle was published for the pinned commit.  Requires quint + python3.
#
#   SPECS_BUNDLE=AUTO  fetch when the submodule is clean and a bundle is
#                      available, otherwise build locally (the default)
#   SPECS_BUNDLE=ON    require the fetched bundle (configure error if missing)
#   SPECS_BUNDLE=OFF   always build locally, never fetch
#
# On success this sets, in the including scope:
#   SPECS_BUNDLE_AVAILABLE  ON, and
#   SPECS_BUNDLE_DIR        the per-suite trace root.
# If neither a bundle nor quint is available it leaves SPECS_BUNDLE_AVAILABLE
# OFF; the quint suites then still build their C harnesses but skip the
# trace-driven replay ctests.

set(SPECS_BUNDLE "AUTO" CACHE STRING
    "MBT trace corpus provider: AUTO (fetch-if-clean else build), ON (fetch), OFF (build)")
set_property(CACHE SPECS_BUNDLE PROPERTY STRINGS AUTO ON OFF)

set(SPECS_REGISTRY "ghcr.io/chimera-nas/specs" CACHE STRING
    "OCI registry reference the specs trace bundle is published under")

set(SPECS_BUNDLE_AVAILABLE OFF)
set(_specs_src ${CMAKE_CURRENT_SOURCE_DIR}/ext/specs)

if(NOT EXISTS ${_specs_src}/CMakeLists.txt)
    message(STATUS
        "specs: submodule ext/specs is not checked out "
        "(git submodule update --init ext/specs); MBT trace suites disabled")
    return()
endif()

# --- Submodule commit + working-tree cleanliness ---------------------------
# The bundle is keyed by the submodule's committed HEAD.  "Clean" means the
# submodule's working tree has no local edits: then traces built from that SHA
# match the bundle the specs CI published for the same SHA.  A dirty tree (spec
# development) has no matching published bundle, so it must be built locally.
find_package(Git QUIET)
set(_specs_sha "")
set(_specs_clean FALSE)
set(_specs_git_err "")
if(Git_FOUND)
    # -c safe.directory: CI configures inside a container whose root user does
    # not own the bind-mounted checkout, so git rejects the repository with
    # "detected dubious ownership" and both commands below fail.  That used to
    # be invisible (ERROR_QUIET) and left the sha empty, which skipped the
    # availability probe and disabled every MBT suite without saying why.
    set(_specs_git ${GIT_EXECUTABLE} -c safe.directory=*)
    execute_process(
        COMMAND ${_specs_git} -C ${_specs_src} rev-parse HEAD
        OUTPUT_VARIABLE _specs_sha OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_VARIABLE _specs_git_err ERROR_STRIP_TRAILING_WHITESPACE
        RESULT_VARIABLE _specs_rc)
    if(NOT _specs_rc EQUAL 0)
        set(_specs_sha "")
    endif()
    execute_process(
        COMMAND ${_specs_git} -C ${_specs_src} status --porcelain
        OUTPUT_VARIABLE _specs_dirty OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
    if(_specs_sha AND NOT _specs_dirty)
        set(_specs_clean TRUE)
    endif()
else()
    set(_specs_git_err "git not found")
endif()

set(_specs_ref "${SPECS_REGISTRY}:${_specs_sha}")
find_program(ORAS_BIN oras)

# --- Choose provider -------------------------------------------------------
set(_use_fetch FALSE)
if(SPECS_BUNDLE STREQUAL "ON")
    if(NOT _specs_clean)
        message(WARNING
            "specs: SPECS_BUNDLE=ON but ext/specs has local edits; the fetched "
            "bundle for ${_specs_sha} will not reflect them")
    endif()
    if(NOT ORAS_BIN)
        message(FATAL_ERROR "specs: SPECS_BUNDLE=ON requires oras on PATH")
    endif()
    set(_use_fetch TRUE)
elseif(SPECS_BUNDLE STREQUAL "AUTO")
    if(_specs_clean AND ORAS_BIN AND _specs_sha)
        # Availability probe: does a bundle exist for this exact commit?
        execute_process(
            COMMAND ${ORAS_BIN} manifest fetch ${_specs_ref}
            RESULT_VARIABLE _probe OUTPUT_QUIET ERROR_QUIET)
        if(NOT _probe EQUAL 0)
            # The bundle is public, so retry anonymously with an isolated docker
            # config -- most probe failures on a dev box are a stale/absent
            # credential helper (credsStore) aborting auth, not a missing bundle
            # (fetch_specs_bundle.sh has the same fallback for the actual pull).
            set(_anoncfg ${CMAKE_BINARY_DIR}/specs-bundle/.anon-docker)
            file(MAKE_DIRECTORY ${_anoncfg})
            file(WRITE ${_anoncfg}/config.json "{}\n")
            execute_process(
                COMMAND ${CMAKE_COMMAND} -E env DOCKER_CONFIG=${_anoncfg}
                        ${ORAS_BIN} manifest fetch ${_specs_ref}
                RESULT_VARIABLE _probe OUTPUT_QUIET ERROR_QUIET)
        endif()
        if(_probe EQUAL 0)
            set(_use_fetch TRUE)
        else()
            message(STATUS
                "specs: no published bundle for ${_specs_sha}; building locally")
        endif()
    else()
        # Not reaching the probe at all is the failure that hid this for months:
        # it looks identical to "no bundle published" from the outside.  Name
        # the reason so a CI job that quietly loses its MBT suites says so.
        if(NOT ORAS_BIN)
            message(STATUS
                "specs: oras not on PATH; cannot fetch a prebuilt bundle")
        elseif(NOT _specs_sha)
            message(STATUS
                "specs: cannot read ext/specs HEAD, so no bundle can be "
                "resolved (${_specs_git_err})")
        elseif(NOT _specs_clean)
            message(STATUS
                "specs: ext/specs has local edits; no published bundle matches, "
                "building locally")
        endif()
    endif()
endif()

# --- Fetch provider --------------------------------------------------------
if(_use_fetch)
    set(_bundle_root ${CMAKE_BINARY_DIR}/specs-bundle)
    set(SPECS_BUNDLE_DIR ${_bundle_root}/traces)
    set(_stamp ${_bundle_root}/.fetched)
    add_custom_command(OUTPUT ${_stamp}
        COMMAND ${CMAKE_COMMAND} -E make_directory ${_bundle_root}
        COMMAND ${CMAKE_COMMAND} -E env ORAS=${ORAS_BIN}
                bash ${CMAKE_CURRENT_SOURCE_DIR}/cmake/fetch_specs_bundle.sh
                ${_specs_ref} ${_bundle_root}
        COMMAND ${CMAKE_COMMAND} -E touch ${_stamp}
        COMMENT "specs: fetching prebuilt trace bundle ${_specs_ref}"
        VERBATIM)
    add_custom_target(specs_bundle ALL DEPENDS ${_stamp})
    set(SPECS_BUNDLE_AVAILABLE ON)
    message(STATUS "specs: using prebuilt trace bundle ${_specs_ref}")
    return()
endif()

# --- Local-build provider --------------------------------------------------
find_program(QUINT_BIN quint)
if(NOT QUINT_BIN)
    message(STATUS
        "specs: quint not found and no prebuilt bundle available; MBT trace "
        "suites disabled (npm i -g @informalsystems/quint@$(cat "
        "ext/specs/.quint-version), or publish/fetch a bundle)")
    return()
endif()

# Build the specs project in-tree.  Its `specs_traces ALL` target generates the
# corpus under ${CMAKE_BINARY_DIR}/ext/specs/traces and its coverage gates join
# chimera's ctest set.  quint (REQUIRED there) is already confirmed present.
add_subdirectory(${_specs_src} ${CMAKE_BINARY_DIR}/ext/specs)
set(SPECS_BUNDLE_DIR ${CMAKE_BINARY_DIR}/ext/specs/traces)
set(SPECS_BUNDLE_AVAILABLE ON)
message(STATUS "specs: building trace corpus locally from ext/specs")
