/* SPDX-FileCopyrightText: 2026 Chimera-NAS Project Contributors
 *
 * SPDX-License-Identifier: LGPL-2.1-only
 *
 * Shared trace-argument collection for the MBT replay harnesses.  The corpus
 * is generated by the chimera-nas/specs repo and consumed here either as a
 * fetched bundle or a local build; either way the chimera build points a
 * replay ctest at a directory of ITF traces rather than enumerating each file
 * at configure time (the files do not exist until the bundle is built/fetched
 * during the build).  A replayer therefore accepts:
 *
 *   --trace <file>            a single trace (back-compat with the old wiring)
 *   --trace-dir <dir>         every *.itf.json in <dir>, sorted for a stable
 *                             deterministic replay order
 *   --exclude-prefix <p>      skip trace files whose basename starts with <p>
 *                             (e.g. the posix memfs batch excludes the
 *                             nfs3_/nfs4_/disk_ profiles that share a dir)
 *
 * mbt_collect_traces() gathers them into a malloc'd, NUL-terminated-free array;
 * unrelated flags are ignored so each main keeps its own option parsing.
 */

#ifndef CHIMERA_MBT_TRACE_DIR_H
#define CHIMERA_MBT_TRACE_DIR_H

#include <dirent.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static int
mbt_pathcmp(
    const void *a,
    const void *b)
{
    return strcmp(*(const char *const *) a, *(const char *const *) b);
} /* mbt_pathcmp */

/* Returns a malloc'd array of malloc'd trace paths; *count receives the length.
 * The caller owns both the array and the strings. */
static char **
mbt_collect_traces(
    int    argc,
    char **argv,
    int   *count)
{
    char      **paths = NULL;
    size_t      n = 0, cap = 0;
    const char *excl[32];
    int         nexcl = 0, i, e;

    for (i = 1; i < argc; i++) {
        if (strcmp(argv[i], "--exclude-prefix") == 0 && i + 1 < argc &&
            nexcl < 32) {
            excl[nexcl++] = argv[++i];
        }
    }

    for (i = 1; i < argc; i++) {
        if (strcmp(argv[i], "--trace") == 0 && i + 1 < argc) {
            if (n == cap) {
                cap   = cap ? cap * 2 : 64;
                paths = realloc(paths, cap * sizeof(*paths));
            }
            paths[n++] = strdup(argv[++i]);
        } else if (strcmp(argv[i], "--trace-dir") == 0 && i + 1 < argc) {
            const char    *dir = argv[++i];
            DIR           *d   = opendir(dir);
            struct dirent *de;
            char         **loc = NULL;
            size_t         ln = 0, lc = 0, j;

            if (!d) {
                continue;
            }
            while ((de = readdir(d)) != NULL) {
                const char *nm = de->d_name;
                size_t      l  = strlen(nm);
                char        path[4096];
                int         skip = 0;

                if (l < 9 || strcmp(nm + l - 9, ".itf.json") != 0) {
                    continue;
                }
                for (e = 0; e < nexcl; e++) {
                    if (strncmp(nm, excl[e], strlen(excl[e])) == 0) {
                        skip = 1;
                        break;
                    }
                }
                if (skip) {
                    continue;
                }
                snprintf(path, sizeof(path), "%s/%s", dir, nm);
                if (ln == lc) {
                    lc  = lc ? lc * 2 : 64;
                    loc = realloc(loc, lc * sizeof(*loc));
                }
                loc[ln++] = strdup(path);
            }
            closedir(d);
            qsort(loc, ln, sizeof(*loc), mbt_pathcmp);
            for (j = 0; j < ln; j++) {
                if (n == cap) {
                    cap   = cap ? cap * 2 : 64;
                    paths = realloc(paths, cap * sizeof(*paths));
                }
                paths[n++] = loc[j];
            }
            free(loc);
        }
    }

    *count = (int) n;
    return paths;
} /* mbt_collect_traces */

#endif /* CHIMERA_MBT_TRACE_DIR_H */
