name: PR Preview Deploy

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "docs/**"
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to deploy preview for'
        required: true
        type: number

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy-preview:
    name: Deploy PR Preview
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: docs
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
          cache-version: 0
          working-directory: '${{ github.workspace }}/docs'

      - name: Set PR number
        id: pr
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "number=${{ inputs.pr_number }}" >> $GITHUB_OUTPUT
          else
            echo "number=${{ github.event.number }}" >> $GITHUB_OUTPUT
          fi

      - name: Build Jekyll site
        run: bundle exec jekyll build --baseurl "/pr-${{ steps.pr.outputs.number }}"
        env:
          JEKYLL_ENV: development

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create preview directory
        run: |
          mkdir -p gh-pages/pr-${{ steps.pr.outputs.number }}
          cp -r docs/_site/* gh-pages/pr-${{ steps.pr.outputs.number }}/

      - name: Commit and push preview
        run: |
          cd gh-pages
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Deploy preview for PR #${{ steps.pr.outputs.number }}"
            git push
          fi

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = ${{ steps.pr.outputs.number }};
            const comment = `## 📖 Documentation Preview
            
            The documentation for this PR has been deployed and is available at:
            
            🔗 **Preview URL:** https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/pr-${prNumber}/
            
            The preview will be updated automatically when you push new commits to this PR.
            
            ✨ *This preview will be automatically cleaned up when the PR is merged or closed.*`;
            
            github.rest.issues.createComment({
              issue_number: prNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });

  cleanup-preview:
    name: Cleanup PR Preview
    runs-on: ubuntu-24.04
    if: github.event.action == 'closed'
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Remove preview directory
        run: |
          if [ -d "pr-${{ github.event.number }}" ]; then
            rm -rf pr-${{ github.event.number }}
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "Cleanup preview for PR #${{ github.event.number }}" || echo "Nothing to cleanup"
            git push || echo "Nothing to push"
          fi 